# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Export modpack

on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install packwiz
      run: go install github.com/packwiz/packwiz@v0.0.0-20250119231123-241f24b550f6

    - name: Export to mrpack
      run: packwiz modrinth export -o modpack.mrpack
    - name: Create Release
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
      with:
        files: modpack.mrpack
    
